------------------LLENAR TABLA TITULO------------------
INSERT INTO TITULO(TITULO)
SELECT DISTINCT TITULO_DEL_EMPLEADO
FROM TEMPORAL
where TITULO_DEL_EMPLEADO is not null
;


------------------LLENAR TABLA EMPLEADO------------------
INSERT INTO EMPLEADO (NOMBRE, APELLIDO, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ID_TITULO)

SELECT DISTINCT TT.NOMBRE_EMPLEADO, TT.APELLIDO_EMPLEADO, TT.DIRECCION_EMPLEADO,
                TT.TELEFONO_EMPLEADO, TT.FECHA_NACIMIENTO_EMPLEADO, TT.GENERO_EMPLEADO,
                T.ID_TITULO
FROM TEMPORAL TT
	inner join TITULO T on T.TITULO = TT.TITULO_DEL_EMPLEADO
where       TT.NOMBRE_EMPLEADO is not null
        and TT.APELLIDO_EMPLEADO is not null
        and TT.DIRECCION_EMPLEADO is not null
        and TT.TELEFONO_EMPLEADO is not null
        and TT.FECHA_NACIMIENTO_EMPLEADO is not null
        and TT.GENERO_EMPLEADO is not null
        and TT.TITULO_DEL_EMPLEADO is not null
;


------------------LLENAR TABLA PACIENTE------------------
INSERT INTO PACIENTE (NOMBRE, APELLIDO, DIRECCION, TELEFONO, FECHA_NACIMIENTO, GENERO, ALTURA, PESO)
SELECT DISTINCT TT.NOMBRE_PACIENTE, TT.APELLIDO_PACIENTE, TT.DIRECCION_PACIENTE,
                TT.TELEFONO_PACIENTE, TT.FECHA_NACIMIENTO_PACIENTE, TT.GENERO_PACIENTE, TT.ALTURA, TT.PESO
FROM TEMPORAL TT
where       TT.NOMBRE_PACIENTE is not null
        and TT.APELLIDO_PACIENTE is not null
        and TT.DIRECCION_PACIENTE is not null
        and TT.TELEFONO_PACIENTE is not null
        and TT.FECHA_NACIMIENTO_PACIENTE is not null
        and TT.GENERO_PACIENTE is not null
        and TT.ALTURA is not null
        and TT.PESO is not null
;


------------------LLENAR TABLA TRATAMIENTO------------------
INSERT INTO TRATAMIENTO(NOMBRE_TRATAMIENTO)
SELECT DISTINCT TRATAMIENTO_APLICADO
FROM TEMPORAL
where TRATAMIENTO_APLICADO is not null
;


------------------LLENAR TABLA PACIENTE_TRATAMIENTO------------------
INSERT INTO PACIENTE_TRATAMIENTO(FECHA_TRATAMIENTO, ID_TRATAMIENTO, ID_PACIENTE)
SELECT DISTINCT TT.FECHA_TRATAMIENTO,T.ID_TRATAMIENTO, P.ID_PACIENTE
FROM TEMPORAL TT
    inner join PACIENTE P on NOMBRE_PACIENTE = P.NOMBRE
                         and APELLIDO_PACIENTE = P.APELLIDO
    inner join TRATAMIENTO T on TRATAMIENTO_APLICADO = T.NOMBRE_TRATAMIENTO
;


------------------LLENAR TABLA EVALUACION------------------
INSERT INTO EVALUACION (FECHA_EVALUACION, ID_EMPLEADO, ID_PACIENTE)
SElECT DISTINCT TT.FECHA_EVALUACION, E.ID_EMPLEADO, P.ID_PACIENTE
from TEMPORAL TT
    inner join EMPLEADO E on NOMBRE_EMPLEADO = E.NOMBRE
                         and APELLIDO_EMPLEADO = E.APELLIDO
    inner join PACIENTE P on NOMBRE_PACIENTE = P.NOMBRE
                         and APELLIDO_PACIENTE = P.APELLIDO
where FECHA_EVALUACION is not null;


------------------LLENAR TABLA DIAGNOSTICO------------------
INSERT INTO DIAGNOSTICO(NOMBRE_DIAGNOSTICO)
SELECT DISTINCT DIAGNOSTICO_DEL_SINTOMA
FROM TEMPORAL
where   RANGO_DEL_DIAGNOSTICO is not null
    and DIAGNOSTICO_DEL_SINTOMA is not null
;


------------------LLENAR TABLA SINTOMA------------------
INSERT INTO SINTOMA(NOMBRE_SINTOMA)
SELECT DISTINCT SINTOMA_DEL_PACIENTE
FROM TEMPORAL
where   SINTOMA_DEL_PACIENTE is not null
;


------------------LLENAR TABLA SINTOMA_DIAGNOSTICO------------------
INSERT INTO SINTOMA_DIAGNOSTICO(RANGO, ID_SINTOMA, ID_DIAGNOSTICO)
SELECT DISTINCT TT.RANGO_DEL_DIAGNOSTICO ,S.ID_SINTOMA, D.ID_DIAGNOSTICO
FROM TEMPORAL TT
    inner join SINTOMA S on S.NOMBRE_SINTOMA= TT.SINTOMA_DEL_PACIENTE
    inner join DIAGNOSTICO D on D.NOMBRE_DIAGNOSTICO = TT.DIAGNOSTICO_DEL_SINTOMA
;


------------------LLENAR TABLA EVALUACION_SINTOMA------------------
INSERT INTO EVALUACION_SINTOMA(ID_EVALUACION, ID_SINTOMA)
SELECT DISTINCT E.ID_EVALUACION, S.ID_SINTOMA
FROM TEMPORAL TT
    inner join EVALUACION E on E.FECHA_EVALUACION = TT.FECHA_EVALUACION
    inner join SINTOMA S on S.NOMBRE_SINTOMA= TT.SINTOMA_DEL_PACIENTE
;


------------------CONTADORES------------------
select * from
(select count(*) Titulos from TITULO),
(select count(*) Empleados from EMPLEADO),
(select count(*) Pacientes from PACIENTE),
(select count(*) tratamientos from TRATAMIENTO),
(select count(*) Paciente_Tratamiento from PACIENTE_TRATAMIENTO),
(select count(*) Evaluaciones from EVALUACION),
(select count(*) Diagnosticos from DIAGNOSTICO),
(select count(*) Sintomas from SINTOMA),
(select count(*) Sintoma_Diagnostico from SINTOMA_DIAGNOSTICO),
(select count(*) Evaluacion_Sintoma from EVALUACION_SINTOMA);

