--Consulta 1--
SELECT E.NOMBRE, E.APELLIDO, E.TELEFONO, count(EV.ID_PACIENTE) Cantidad_de_Pacientes
FROM EVALUACION EV
inner join EMPLEADO E on E.ID_EMPLEADO = EV.ID_EMPLEADO
GROUP BY  E.NOMBRE, E.APELLIDO, E.TELEFONO
ORDER BY Cantidad_de_Pacientes DESC
;


--Consulta 2--
SELECT E1.NOMBRE, E1.APELLIDO, E1.DIRECCION, T.TITULO
FROM Empleado E1
inner join TITULO T on E1.ID_TITULO = T.ID_TITULO
WHERE E1.genero = 'M' and 3 < (
    SELECT count(*) as atentidos
    FROM Empleado E2
    inner join EVALUACION EV on EV.ID_EMPLEADO = E2.ID_EMPLEADO
    inner join PACIENTE P on EV.ID_PACIENTE = P.ID_PACIENTE
    inner join EVALUACION_SINTOMA ES on ES.ID_EVALUACION = EV.ID_EVALUACION
    WHERE extract(year from ES.FECHA_EVALUACION) = '2016' and E1.id_empleado = E2.id_empleado
    GROUP BY E2.NOMBRE, E2.APELLIDO
)
group by E1.NOMBRE, E1.APELLIDO, E1.DIRECCION, T.TITULO
order by E1.NOMBRE asc;


--Consulta 3--
SELECT DISTINCT P.NOMBRE, P.APELLIDO
FROM PACIENTE P
inner join PACIENTE_TRATAMIENTO PT on P.ID_PACIENTE = PT.ID_PACIENTE
inner join TRATAMIENTO T on PT.ID_TRATAMIENTO = T.ID_TRATAMIENTO
inner join EVALUACION E on P.ID_PACIENTE = E.ID_PACIENTE
inner join EVALUACION_SINTOMA ES on ES.ID_EVALUACION = E.ID_EVALUACION
inner join SINTOMA S on ES.ID_SINTOMA = S.ID_SINTOMA
where T.NOMBRE_TRATAMIENTO = 'Tabaco en polvo' and S.NOMBRE_SINTOMA = 'Dolor de cabeza'
;


--Consulta 4--
SELECT P.NOMBRE, P.APELLIDO, count(*) Cantidad
FROM PACIENTE P
inner join PACIENTE_TRATAMIENTO PT on P.ID_PACIENTE = PT.ID_PACIENTE
inner join TRATAMIENTO T on PT.ID_TRATAMIENTO = T.ID_TRATAMIENTO
where T.NOMBRE_TRATAMIENTO = 'Antidepresivos'
  and ROWNUM <= 5
GROUP BY P.NOMBRE, P.APELLIDO
ORDER BY Cantidad DESC
;


--Consulta 5--
SELECT P1.NOMBRE, P1.APELLIDO, P1.DIRECCION, A2.CANTIDAD
FROM PACIENTE P1, (
    SELECT P2.ID_PACIENTE, P2.NOMBRE, P2.APELLIDO, P2.DIRECCION, count(*) CANTIDAD
    FROM PACIENTE P2
    inner join PACIENTE_TRATAMIENTO PT on P2.ID_PACIENTE = PT.ID_PACIENTE
    inner join TRATAMIENTO T on T.ID_TRATAMIENTO = PT.ID_TRATAMIENTO
    group by P2.ID_PACIENTE, P2.NOMBRE, P2.APELLIDO, P2.DIRECCION
) A2, EVALUACION E
where P1.ID_PACIENTE = A2.ID_PACIENTE
    and 3 < A2.CANTIDAD
    and P1.ID_PACIENTE not in (
        SELECT id_paciente from Evaluacion
    )
group by P1.NOMBRE, P1.APELLIDO, P1.DIRECCION, A2.CANTIDAD
;


--Consulta 6--
--Consulta 7--
--Consulta 8--
--Consulta 9--
--Consulta 10--
--Consulta 11--